import { Info } from "lucide-react";

function SettingsSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div
      style={{
        background: "#fff",
        border: "1px solid #e2e8f0",
        borderRadius: 14,
        overflow: "hidden",
        marginBottom: 16,
        boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
      }}
    >
      <div style={{ padding: "14px 20px", borderBottom: "1px solid #f1f5f9", background: "#f8fafc" }}>
        <h3 style={{ fontWeight: 700, fontSize: "0.9375rem", color: "#0f172a" }}>{title}</h3>
      </div>
      <div style={{ padding: "20px" }}>{children}</div>
    </div>
  );
}

function SettingsField({ label, value, type = "text" }: { label: string; value: string; type?: string }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <label className="form-label">{label}</label>
      <input
        type={type}
        className="form-input"
        defaultValue={value}
        style={{ background: "#f8fafc", cursor: "not-allowed", fontSize: "0.875rem" }}
        readOnly
        aria-label={label}
      />
    </div>
  );
}

function ToggleSetting({ label, description, enabled }: { label: string; description: string; enabled: boolean }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", padding: "14px 0", borderBottom: "1px solid #f1f5f9" }}>
      <div>
        <div style={{ fontWeight: 600, fontSize: "0.875rem", color: "#0f172a" }}>{label}</div>
        <div style={{ fontSize: "0.8rem", color: "#64748b", marginTop: 2 }}>{description}</div>
      </div>
      <div
        style={{
          width: 40,
          height: 22,
          borderRadius: 11,
          background: enabled ? "#3b5bdb" : "#e2e8f0",
          position: "relative",
          flexShrink: 0,
          marginLeft: 16,
          cursor: "default",
        }}
        role="switch"
        aria-checked={enabled}
        aria-label={label}
      >
        <div
          style={{
            position: "absolute",
            width: 16,
            height: 16,
            borderRadius: "50%",
            background: "#fff",
            top: 3,
            left: enabled ? 21 : 3,
            transition: "left 0.2s ease",
            boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
          }}
        />
      </div>
    </div>
  );
}

export default function Settings() {
  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 4 }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 800, color: "#0f172a" }}>Settings</h2>
          <span className="badge badge-blue" style={{ fontSize: "0.65rem" }}>Demo Configuration</span>
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "flex-start",
            gap: 8,
            padding: "10px 14px",
            background: "rgba(59,91,219,0.06)",
            borderRadius: 10,
            border: "1px solid rgba(59,91,219,0.15)",
          }}
        >
          <Info size={14} color="#3b5bdb" style={{ marginTop: 1, flexShrink: 0 }} />
          <p style={{ fontSize: "0.8125rem", color: "#475569" }}>
            This is an interactive demo configuration panel. These settings are not connected to a live backend. Fields are read-only for demonstration purposes.
          </p>
        </div>
      </div>

      <SettingsSection title="Company Information">
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 0 }}>
          <SettingsField label="Company Name" value="Demo Corp Pvt. Ltd." />
          <SettingsField label="Company Logo" value="logo_demo_corp.png" />
          <SettingsField label="Currency" value="INR (₹)" />
          <SettingsField label="Footer Text" value="Generated by PayFlow Automate" />
        </div>
      </SettingsSection>

      <SettingsSection title="Payslip Template">
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 0 }}>
          <SettingsField label="Template Style" value="Professional — Standard" />
          <SettingsField label="Payslip Layout" value="Two-column with logo header" />
          <SettingsField label="Font Family" value="Inter / Helvetica" />
        </div>
      </SettingsSection>

      <SettingsSection title="Email Configuration">
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 0 }}>
          <SettingsField label="Sender Name" value="Payroll Team" />
          <SettingsField label="Email Subject" value="Your Payslip for {Month} {Year}" />
          <SettingsField label="Email Provider" value="Custom SMTP / Configured" />
        </div>
      </SettingsSection>

      <SettingsSection title="Notification Settings">
        <ToggleSetting label="Email delivery confirmation" description="Receive a summary report after payroll processing." enabled={true} />
        <ToggleSetting label="Failed delivery alerts" description="Get notified when an employee email fails to deliver." enabled={true} />
        <ToggleSetting label="Processing log export" description="Auto-export processing logs after each payroll run." enabled={false} />
      </SettingsSection>

      <SettingsSection title="Security">
        <ToggleSetting label="Sensitive data protection" description="Mask or restrict access to sensitive employee fields during processing." enabled={true} />
        <ToggleSetting label="Payslip password protection" description="Apply access controls to generated payslip documents." enabled={true} />
        <ToggleSetting label="Document access logging" description="Track who accessed generated documents." enabled={false} />
      </SettingsSection>
    </div>
  );
}
